[build]
  publish = "_site"
  command = "npm run build"
[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "./_site/img/cache",
    ".cache"
  ]

[[plugins]]
package = "netlify-plugin-debug-cache"
