//= require "jquery/dist/jquery.js"
//= require "lib/modernizr.js"
//= require "filament-fixed/fixedfixed.js"
//= require "picturefill/src/picturefill.js"
//= require "waypoints/lib/jquery.waypoints.js"
//= require "waypoints/lib/shortcuts/inview.js"
//= require "skrollr/src/skrollr.js"
//= require "tablesaw/dist/stackonly/tablesaw.stackonly.js"
